name: 🚀 Deploy Server

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]*"
      - "v[0-9]+.[0-9]+.[0-9]"

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: duofiction # the name of the project on Deno Deploy
          entrypoint: duofiction.main.ts # the entrypoint to deploy
